### ISSUE TITLE
Needs Motivation and Background section

### ISSUE THREAD

**Issue by plehegar** [w3cping/administrivia#30]
Motivation and Background section is empty and we need one

**Comment by samuelweiler** [comment]
Substantively, is this needed here?  (Maybe it is, to explain this history of IG-->WG?) If not, don't merely add duplicative text?  (As context, see https://github.com/w3c/charter-drafts/issues/383#issuecomment-1582358689)

**Comment by svgeesus** [comment]
Substantively, we had multiple AC reps tell us to stop putting historical background and motivating use cases into the Scope section, because every word in Scope gets pored over by lawyers determining RF patent exposure while the rest is not. That was the reason for the template change.

If AC Reps keep seeing charters which ignore their feedback, they either get annoyed and become more assertive or resigned and less involved. Neither is a desirable outcome.

**Comment by jyasskin** [comment]
FWIW, @svgeesus, I don't see Sam asking to add extra things into the Scope section, just to avoid duplicating information into the Motivation and Background section. I think your comments are completely compatible, and 👍 to both of them.

**Comment by plehegar** [comment]
See https://github.com/w3cping/administrivia/commit/028b7307d3e76779d5cdec73186ba9e959b83533

**Comment by npdoty** [comment]
Added a motivation and background section which gives justification for the dual-sided mission and some context about the shift from PING. This is non-duplicative of the mission, and gives some of the history.

Closing this issue as the section has been added now, but of course reviewers can open issues for comments on the text of that section.
