### ISSUE TITLE
Needs to mention the work on horizontal reviews

### ISSUE THREAD

**Issue by plehegar** [w3cping/administrivia#31]
Since the Privacy WG will replace PING, we need to list this in the non-deliverable section

**Comment by plehegar** [comment]
Use the [i18n WG charter as sample](https://www.w3.org/International/groups/wg/charter.html).

**Comment by jyasskin** [comment]
I've heard some concerns about the status of reviews provided by members of the PING. The process tends to go:
1. WG files for horizontal review.
2. PING delegates the review to an individual.
3. The individual reports back to the PING, which discusses the review.
4. The PING approves some or all of the concerns in the review and delegates back to the individual to file issues and generally represent the PING back to the WG when trying to get the issues resolved.
5. The WG discusses the issues and either resolves them to its satisfaction or identifies some information the PING didn't consider that means a concern actually isn't a problem.

If the PING's delegate disagrees with the WG's resolution, it's sometimes unclear to what extent that's an individual opinion vs an accurate summary of the PING's overall consensus. It's also unclear what a WG needs to do in order to resolve that confusion. In [one recent case](https://github.com/gpuweb/gpuweb/issues/3101#issuecomment-1559442029), the WG asked to talk directly to the PING as a whole and was refused.

It'd be good if the Privacy WG's charter would give WGs some help in navigating this part of their interactions with horizontal reviews.

**Comment by jyasskin** [comment]
I don't think the "give WGs some help" text has to be in specifically this WG's charter. If it's added to https://www.w3.org/Guide/documentreview/, for example, and this WG's charter links there, that'd be fine.

**Comment by plehegar** [comment]
We already have [How to Conduct a PING Privacy Review](https://github.com/w3c/ping/blob/main/howto-conduct-a-privacy-review.md).

We should be revised it to include the WG if the PING reviewer wants to raise a formal objection. It's important to know the position of the Privacy WG if a formal objection gets raised related to privacy.

We should link it from the charter.

@npdoty is looking into making a PR for these.

**Comment by npdoty** [comment]
Draft charter links to that How To documentation now, and @pes10k [has also updated that documentation](https://github.com/w3c/ping/pull/193) to indicate that issues should be brought back to wider group discussion if they can't be resolved and would lead to a formal objection -- with the goals of resolving the issue and, secondarily, of documenting the positions if there will be a formal objection that a council would need to review.

@jyasskin I believe that addresses the process concern you're noting, in addition to the point about explicitly noting the horizontal review work. Please take a look!

**Comment by jyasskin** [comment]
Yep, that How To documentation seems like a reasonable way to explain this to WGs, even though it's aimed at the reviewer instead of the WG.
