### ISSUE TITLE
Consider whether IE should have Member access or not

### ISSUE THREAD

**Issue by plehegar** [w3cping/administrivia#34]
By default, all invited experts will have Member access unless otherwise noted in the Group charter.

This issue is just to make sure we considered that question.

**Comment by pes10k** [comment]
+1 from me, i agree with @sandandsnow

**Comment by npdoty** [comment]
No particular reason to prohibit Member access (even though we think it shouldn't have an effect either way since work is done in public), so we will remove that expectation and just follow what the AB has suggested should be the default, that IEs get Member access unless there's some particular reason.

**Comment by npdoty** [comment]
(confirmed on 7 December PING call)
