### ISSUE TITLE
Hook into TAG process

### ISSUE THREAD

**Issue by jasonanovak** [w3cping/administrivia#5]
To get engaged in privacy reviews sooner than CR, we should hook into the TAG process for reviews.

**Comment by jasonanovak** [comment]
Per TPAC f2f, over to @tjwhalen

**Comment by samuelweiler** [comment]
I spoke with @swickr (W3C's [Architecture and Technology](https://www.w3.org/2016/08/2016-reorg.html#h.icr45wucrm9i) lead) re: whether other horizontal areas (i18n, a11y) would also be interested in hooking in at this (= blink intents or similar) stage.  He's more concerned that reviews are not happening reliably during the normal standards process, and he wants to focus his efforts there. 

Accordingly, it sounds like PING is on its own for now with respect to pre-CR reviews.   Tagging @swickr in case I've misunderstood his response.

**Comment by samuelweiler** [comment]
tagging @michael-n-cooper in case he's interested.

**Comment by tjwhalen** [comment]
WICG ["why-see-gee"]:
-- Chris W and I spoke January 8th; co-chair Yoav now works at Google also but was not available for our chat; the third chair is Marcos Caceros@Mozilla
-- Chris explained a bunch about their activities and processes, and we focused on the places where PING might best hook in. 
-- Takeaways were mainly that PING might benefit from being alerted by the WICG chairs when:
* WICG transitions a proposal to a repo [aka "this is getting more serious"] if it appears to have significant potential privacy issues
* when an effort graduates from incubation to a new or existing WG...which, if I understood correctly, would also involve the WICG chairs since they have to move a repo so they would at least be aware of this stage. (Unlike the previous step, this is really just a side effect of managing the data, rather than something in the mainstream process, but whatever works! It seems reliable.)

Chris seemed happy to collaborate in this task, but this would require us to be in better sync with those chairs, since we are dependent on their eyes and ears to flag things of interest. This has the advantage, though, of cutting through the noise a great deal, since there is a *lot* of stuff flying through WICG at various levels of maturity. Just having a quick email to chairs would be enough, probably? Happy to take suggestions on lightweight communication processes.

TAG review
Chris W also said I should talk to Alex Russell re: TAG and also blink-intent, so I did that Jan 9. Alex R is leaving the TAG and Alice Boxhall is joining - she is also at Google so he invited her to join our chat.

-- takeways:
* Alex shared a diagram that helped clarify the overall process:
![image](https://user-images.githubusercontent.com/5987608/52577089-65cedc00-2def-11e9-9ba5-d3059371e620.png)

* as far as Chromium is concerned, things that go to intent-to-implement also go to TAG review. So it's probably redundant to monitor the blink-intent stream -- e.g., the bot (@intenttoship) -- given the same stuff will appear in the TAG Design Review stack (https://github.com/w3ctag/design-reviews). Any browser not using blink-intent...? Well, they can still ask for a TAG review, although this doesn't happen much in practice. Also this whole process isn't very strong on "enforcement" but is better than it used to be, and will capture a lot (if not *everything*.)
* the w3ctag/design-reviews is very open and anybody can subscribe and comment and are indeed hugely encouraged to do so (including PING, naturally!)
* Alex seemed to think that coordinating TAG and PING reviews would be a Good Thing. They have been focused on the more checklist/concrete types of guidance but the privacy stuff has been much more complicated and it might unstick things to get our expertise going early.
* Alice also emailed me to follow up coordination efforts in her new TAG role.

Re: blink-intent
--  I am following the bot on Twitter, had a look at the stream. It seems fine and not that "noisy" but given what Alex said, it might be redundant to pay close attention to if we are hooked into TAG process which will capture this anyhow. (Note that the bot tweets "when browser makers announce their intent to ship, change or remove features" so it's not all *new* stuff.)
